services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - ${HOME}/.claude:/home/claude/.claude
    working_dir: /workspace
    command: sleep infinity
    ports:
      - "5001:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://taskmanager:taskmanager@postgres:5432/taskmanager_dev
      - REDIS_URL=redis://redis:6379/0

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: taskmanager
      POSTGRES_DB: taskmanager_dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"